// MLC adapter — matches the structure of The MLC's published "Bulk Work
// Registration Spreadsheet Template" (themlc.com).
//
// Structure:
//   - One row per WORK (= composition)
//   - Writer info in numbered columns: "Writer 1 First Name", "Writer 1 Last Name",
//     "Writer 1 IPI", "Writer 1 Society", "Writer 1 Capacity", "Writer 1 Share %"
//     ...repeating up to the maximum writer count for any work in this release.
//   - Original Publisher info in numbered columns mirroring the writer block.
//
// We also emit a JSON dump and a README sheet inside the workbook.

import type { ReleaseContext } from '@/lib/validation/catalog-validation';
import { archiveFile } from '@/lib/files/workbookArchive';
import {
  buildXlsx, fmtDurationHHMMSS, mlcCapacityFromRole, safeSlug, splitName,
  type Sheet,
} from '@/lib/export/spreadsheet';
import type { GeneratedFile } from '@/types/exports';

function build(ctx: ReleaseContext) {
  const writerById = new Map(ctx.writers.map((w) => [w.id, w]));
  const publisherById = new Map(ctx.publishers.map((p) => [p.id, p]));
  const r = ctx.release;

  let maxWriters = 0;
  let maxPublishers = 0;
  for (const t of ctx.tracks) {
    maxWriters = Math.max(maxWriters, ctx.trackWriters.filter((x) => x.track_id === t.id).length);
    maxPublishers = Math.max(maxPublishers, ctx.trackPublishers.filter((x) => x.track_id === t.id).length);
  }

  const baseHeaders = [
    'Work Title', 'Alternate Titles', 'ISWC', 'Language', 'Instrumental (Y/N)',
    'Duration (HH:MM:SS)', 'Recording Title', 'Recording Artist', 'ISRC',
    'Release Title', 'Release Date', 'UPC', 'Label',
  ];
  const writerHeaders: string[] = [];
  for (let i = 1; i <= Math.max(maxWriters, 1); i++) {
    writerHeaders.push(
      `Writer ${i} First Name`, `Writer ${i} Middle Name`, `Writer ${i} Last Name`,
      `Writer ${i} IPI`, `Writer ${i} Society`, `Writer ${i} Capacity (CA/C/A)`, `Writer ${i} Share %`,
    );
  }
  const publisherHeaders: string[] = [];
  for (let i = 1; i <= Math.max(maxPublishers, 1); i++) {
    publisherHeaders.push(
      `Original Publisher ${i} Name`, `Original Publisher ${i} IPI`,
      `Original Publisher ${i} Society`, `Original Publisher ${i} Share %`,
    );
  }
  const headers = [...baseHeaders, ...writerHeaders, ...publisherHeaders];

  const rows: Record<string, unknown>[] = [];
  for (const t of ctx.tracks) {
    const writers = ctx.trackWriters.filter((x) => x.track_id === t.id);
    const publishers = ctx.trackPublishers.filter((x) => x.track_id === t.id);
    const row: Record<string, unknown> = {
      'Work Title': t.track_title,
      'Alternate Titles': t.version ?? '',
      'ISWC': t.iswc ?? '',
      'Language': t.language ?? '',
      'Instrumental (Y/N)': t.instrumental ? 'Y' : 'N',
      'Duration (HH:MM:SS)': fmtDurationHHMMSS(t.duration_ms),
      'Recording Title': t.track_title,
      'Recording Artist': r.primary_artist ?? '',
      'ISRC': t.isrc ?? '',
      'Release Title': r.release_title,
      'Release Date': r.release_date ?? '',
      'UPC': r.upc ?? '',
      'Label': r.label_name ?? '',
    };
    writers.forEach((tw, i) => {
      const w = writerById.get(tw.writer_profile_id);
      if (!w) return;
      const { first, middle, last } = splitName(w.legal_name);
      const n = i + 1;
      row[`Writer ${n} First Name`] = first;
      row[`Writer ${n} Middle Name`] = middle;
      row[`Writer ${n} Last Name`] = last;
      row[`Writer ${n} IPI`] = w.ipi_number ?? '';
      row[`Writer ${n} Society`] = w.pro ?? '';
      row[`Writer ${n} Capacity (CA/C/A)`] = mlcCapacityFromRole(tw.role);
      row[`Writer ${n} Share %`] = Number(tw.share_percent).toFixed(2);
    });
    publishers.forEach((tp, i) => {
      const p = publisherById.get(tp.publisher_profile_id);
      if (!p) return;
      const n = i + 1;
      row[`Original Publisher ${n} Name`] = p.publisher_name;
      row[`Original Publisher ${n} IPI`] = p.ipi_number ?? '';
      row[`Original Publisher ${n} Society`] = p.pro ?? '';
      row[`Original Publisher ${n} Share %`] = Number(tp.share_percent).toFixed(2);
    });
    rows.push(row);
  }

  const readme: Sheet = {
    name: 'README',
    headers: ['Field', 'Notes'],
    rows: [
      { Field: 'Source', Notes: `Generated by LevelUp Publishing on ${new Date().toISOString()}` },
      { Field: 'Layout', Notes: 'Matches the structure of The MLC bulk Work Registration template — verify the latest version at themlc.com before uploading.' },
      { Field: 'Capacity codes', Notes: 'CA = composer & author, C = composer (music only), A = author (lyrics only)' },
      { Field: 'Duration', Notes: 'HH:MM:SS as required by MLC' },
      { Field: 'Shares', Notes: 'Writer shares should sum to 100. Publisher shares should sum to 100.' },
      { Field: 'Society', Notes: 'PRO affiliation: BMI, ASCAP, SESAC, GMR, or international equivalent' },
    ],
  };

  return {
    sheets: [{ name: 'Works', headers, rows }, readme] as Sheet[],
    json: {
      generated_at: new Date().toISOString(),
      release: { title: r.release_title, artist: r.primary_artist, upc: r.upc, label: r.label_name },
      works: rows,
    },
  };
}

export async function mlcGenerate(opts: {
  orgId: string; releaseId: string; createdBy: string | null; ctx: ReleaseContext;
}): Promise<GeneratedFile[]> {
  const { sheets, json } = build(opts.ctx);
  const slug = safeSlug(opts.ctx.release.release_title);
  const xlsx = await buildXlsx(sheets);

  const xlsxFile = await archiveFile({
    orgId: opts.orgId, releaseId: opts.releaseId, platform: 'mlc',
    fileName: `MLC_Bulk_Work_Registration_${slug}.xlsx`, fileType: 'workbook_xlsx',
    buffer: xlsx, contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    createdBy: opts.createdBy, notes: 'Matches MLC bulk work registration template layout.',
  });
  const jsonFile = await archiveFile({
    orgId: opts.orgId, releaseId: opts.releaseId, platform: 'mlc',
    fileName: `MLC_Bulk_Work_Registration_${slug}.json`, fileType: 'data_json',
    buffer: Buffer.from(JSON.stringify(json, null, 2), 'utf-8'),
    contentType: 'application/json; charset=utf-8',
    createdBy: opts.createdBy,
  });
  return [xlsxFile, jsonFile].filter((f): f is GeneratedFile => !!f);
}
