// SoundExchange adapter — matches the structure of the public Repertoire
// Data Template (soundexchange.com). One row per RECORDING, keyed by ISRC.
// HH:MM:SS duration. P-line as required.

import type { ReleaseContext } from '@/lib/validation/catalog-validation';
import { archiveFile } from '@/lib/files/workbookArchive';
import { buildCsv, buildXlsx, fmtDurationHHMMSS, safeSlug, type Sheet } from '@/lib/export/spreadsheet';
import type { GeneratedFile } from '@/types/exports';

const HEADERS = [
  'ISRC',
  'Sound Recording Title',
  'Sound Recording Title Version',
  'Featured Artist',
  'Album Title',
  'Album Release Date',
  'Original Release Date',
  'UPC',
  'Catalog Number',
  'P Line',
  'Track Duration (HH:MM:SS)',
  'Track Number',
  'Label',
  'Genre',
  'Recording Country',
  'Master Rights Owner',
  'Year of Fixation',
  'Comments',
];

function rowsFor(ctx: ReleaseContext) {
  const r = ctx.release;
  const pLineCombined = r.copyright_year
    ? `℗ ${r.copyright_year} ${r.p_line ?? ''}`.trim()
    : (r.p_line ?? '');
  return ctx.tracks.map((t) => ({
    'ISRC': t.isrc ?? '',
    'Sound Recording Title': t.track_title,
    'Sound Recording Title Version': t.version ?? '',
    'Featured Artist': r.primary_artist ?? '',
    'Album Title': r.release_title,
    'Album Release Date': r.release_date ?? '',
    'Original Release Date': r.original_release_date ?? r.release_date ?? '',
    'UPC': r.upc ?? '',
    'Catalog Number': r.catalog_number ?? '',
    'P Line': pLineCombined,
    'Track Duration (HH:MM:SS)': fmtDurationHHMMSS(t.duration_ms),
    'Track Number': t.track_number ?? '',
    'Label': r.label_name ?? '',
    'Genre': r.genre ?? '',
    'Recording Country': t.recording_location ?? '',
    'Master Rights Owner': r.p_line || r.label_name || r.primary_artist || '',
    'Year of Fixation': r.copyright_year ?? '',
    'Comments': '',
  }));
}

export async function soundexchangeGenerate(opts: {
  orgId: string; releaseId: string; createdBy: string | null; ctx: ReleaseContext;
}): Promise<GeneratedFile[]> {
  const rows = rowsFor(opts.ctx);
  const slug = safeSlug(opts.ctx.release.release_title);
  const csv = buildCsv(HEADERS, rows);
  const readme: Sheet = {
    name: 'README',
    headers: ['Field', 'Notes'],
    rows: [
      { Field: 'Source', Notes: `Generated by LevelUp Publishing on ${new Date().toISOString()}` },
      { Field: 'Layout', Notes: 'Matches SoundExchange Repertoire Data Template column structure. Verify the latest version at soundexchange.com before submitting.' },
      { Field: 'Duration', Notes: 'HH:MM:SS as required by SoundExchange' },
      { Field: 'Featured Artist', Notes: 'The performing artist credited on the master recording (drives the 45% artist royalty split).' },
      { Field: 'Master Rights Owner', Notes: 'The entity that owns the recording — receives the 50% master royalty.' },
    ],
  };
  const xlsx = await buildXlsx([{ name: 'Recordings', headers: HEADERS, rows }, readme]);

  const csvFile = await archiveFile({
    orgId: opts.orgId, releaseId: opts.releaseId, platform: 'soundexchange',
    fileName: `SoundExchange_Repertoire_${slug}.csv`, fileType: 'data_csv',
    buffer: Buffer.from(csv, 'utf-8'), contentType: 'text/csv; charset=utf-8',
    createdBy: opts.createdBy,
  });
  const xlsxFile = await archiveFile({
    orgId: opts.orgId, releaseId: opts.releaseId, platform: 'soundexchange',
    fileName: `SoundExchange_Repertoire_${slug}.xlsx`, fileType: 'workbook_xlsx',
    buffer: xlsx, contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    createdBy: opts.createdBy,
  });
  return [csvFile, xlsxFile].filter((f): f is GeneratedFile => !!f);
}
