import PDFDocument from 'pdfkit';
import type { BMIPacket } from './types';
import type { GeneratedArtifact } from '@/types/exports';

export function renderBMIText(packet: BMIPacket): string {
  const lines: string[] = [];
  lines.push('BMI WORK REGISTRATION PACKET');
  lines.push('Generated by Music Publishing Suite');
  lines.push('Copy each work block into bmi.com/registration');
  lines.push('='.repeat(60));
  packet.works.forEach((work, i) => {
    lines.push('');
    lines.push(`--- Work ${i + 1}: ${work.workTitle} ---`);
    if (work.alternateTitles.length) lines.push(`Alternate Titles: ${work.alternateTitles.join('; ')}`);
    if (work.durationSeconds != null) lines.push(`Duration: ${formatDuration(work.durationSeconds)}`);
    if (work.language) lines.push(`Language: ${work.language}`);
    if (work.genre) lines.push(`Genre: ${work.genre}`);
    lines.push('Writers:');
    work.writers.forEach((w) => {
      lines.push(`  - ${w.name} | IPI: ${w.ipi || 'MISSING'} | PRO: ${w.pro} | Share: ${w.share}%`);
    });
    lines.push('Publishers:');
    if (work.publishers.length === 0) lines.push('  - (none)');
    work.publishers.forEach((p) => {
      lines.push(`  - ${p.name} | IPI: ${p.ipi || 'MISSING'} | PRO: ${p.pro} | Share: ${p.share}%`);
    });
    if (work.recordingArtist) lines.push(`Recording Artist: ${work.recordingArtist}`);
    if (work.isrc) lines.push(`ISRC: ${work.isrc}`);
    if (work.releaseTitle) lines.push(`Release: ${work.releaseTitle}`);
    if (work.notes) lines.push(`Notes: ${work.notes}`);
  });
  return lines.join('\n');
}

export async function renderBMIPdf(packet: BMIPacket): Promise<Buffer> {
  const doc = new PDFDocument({ size: 'LETTER', margin: 54 });
  const chunks: Buffer[] = [];
  doc.on('data', (c) => chunks.push(c as Buffer));
  const done = new Promise<Buffer>((resolve) => {
    doc.on('end', () => resolve(Buffer.concat(chunks)));
  });

  doc.fontSize(18).text('BMI Work Registration Packet', { underline: true });
  doc.moveDown(0.5);
  doc.fontSize(10).fillColor('#666').text(
    'Copy each work block into bmi.com/registration. Verify all fields before submission.',
  );
  doc.fillColor('#000');

  packet.works.forEach((work, i) => {
    doc.moveDown(1);
    doc.fontSize(13).text(`Work ${i + 1}: ${work.workTitle}`);
    doc.fontSize(10);
    const kv = (k: string, v: string | number | null | undefined) => {
      if (v == null || v === '') return;
      doc.text(`${k}: ${v}`);
    };
    kv('Alternate Titles', work.alternateTitles.join('; '));
    if (work.durationSeconds != null) kv('Duration', formatDuration(work.durationSeconds));
    kv('Language', work.language);
    kv('Genre', work.genre);
    doc.moveDown(0.3);
    doc.text('Writers:');
    work.writers.forEach((w) => {
      doc.text(`  • ${w.name} | IPI: ${w.ipi || 'MISSING'} | PRO: ${w.pro} | Share: ${w.share}%`);
    });
    doc.moveDown(0.2);
    doc.text('Publishers:');
    if (work.publishers.length === 0) doc.text('  (none)');
    work.publishers.forEach((p) => {
      doc.text(`  • ${p.name} | IPI: ${p.ipi || 'MISSING'} | PRO: ${p.pro} | Share: ${p.share}%`);
    });
    kv('Recording Artist', work.recordingArtist);
    kv('ISRC', work.isrc);
    kv('Release', work.releaseTitle);
    kv('Notes', work.notes);
  });

  doc.end();
  return done;
}

export async function generateBMI(packet: BMIPacket): Promise<GeneratedArtifact[]> {
  const pdf = await renderBMIPdf(packet);
  const txt = renderBMIText(packet);
  return [
    { fileName: 'BMI_Registration_Packet.pdf', fileType: 'pdf', buffer: pdf },
    { fileName: 'BMI_Registration_Packet.txt', fileType: 'txt', buffer: Buffer.from(txt, 'utf8') },
  ];
}

function formatDuration(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return `${m}:${String(s).padStart(2, '0')}`;
}
