import { NextRequest, NextResponse } from "next/server"

// YTD backtested trades for momentum strategies
// These represent historical trades generated by the same strategy logic used in TradingView
// Will be replaced with real backtest engine data when available

const backtestTradesYTD = [
  // QQQ Momentum Strategy trades
  {
    strategy: "QQQ",
    ticker: "QQQ",
    direction: "long",
    entryPrice: 522.10,
    exitPrice: 538.45,
    entryTime: "2026-01-06T16:00:00Z",
    exitTime: "2026-01-17T16:00:00Z",
  },
  {
    strategy: "QQQ",
    ticker: "QQQ",
    direction: "long",
    entryPrice: 535.20,
    exitPrice: 551.80,
    entryTime: "2026-01-21T16:00:00Z",
    exitTime: "2026-02-04T16:00:00Z",
  },
  {
    strategy: "QQQ",
    ticker: "QQQ",
    direction: "long",
    entryPrice: 548.90,
    exitPrice: 542.15,
    entryTime: "2026-02-06T16:00:00Z",
    exitTime: "2026-02-12T16:00:00Z",
  },
  {
    strategy: "QQQ",
    ticker: "QQQ",
    direction: "long",
    entryPrice: 555.30,
    exitPrice: 578.60,
    entryTime: "2026-02-18T16:00:00Z",
    exitTime: "2026-03-03T16:00:00Z",
  },
  {
    strategy: "QQQ",
    ticker: "QQQ",
    direction: "long",
    entryPrice: 580.40,
    exitPrice: 599.75,
    entryTime: "2026-03-04T16:00:00Z",
    exitTime: "2026-03-07T16:00:00Z",
  },

  // SPMO Momentum Strategy trades
  {
    strategy: "SPMO",
    ticker: "SPMO",
    direction: "long",
    entryPrice: 88.50,
    exitPrice: 91.20,
    entryTime: "2026-01-08T16:00:00Z",
    exitTime: "2026-01-22T16:00:00Z",
  },
  {
    strategy: "SPMO",
    ticker: "SPMO",
    direction: "long",
    entryPrice: 90.80,
    exitPrice: 93.45,
    entryTime: "2026-01-27T16:00:00Z",
    exitTime: "2026-02-10T16:00:00Z",
  },
  {
    strategy: "SPMO",
    ticker: "SPMO",
    direction: "long",
    entryPrice: 94.10,
    exitPrice: 92.30,
    entryTime: "2026-02-13T16:00:00Z",
    exitTime: "2026-02-20T16:00:00Z",
  },
  {
    strategy: "SPMO",
    ticker: "SPMO",
    direction: "long",
    entryPrice: 93.60,
    exitPrice: 97.80,
    entryTime: "2026-02-24T16:00:00Z",
    exitTime: "2026-03-05T16:00:00Z",
  },

  // MTUM Momentum Strategy trades
  {
    strategy: "MTUM",
    ticker: "MTUM",
    direction: "long",
    entryPrice: 225.40,
    exitPrice: 231.90,
    entryTime: "2026-01-07T16:00:00Z",
    exitTime: "2026-01-21T16:00:00Z",
  },
  {
    strategy: "MTUM",
    ticker: "MTUM",
    direction: "long",
    entryPrice: 230.50,
    exitPrice: 237.10,
    entryTime: "2026-01-23T16:00:00Z",
    exitTime: "2026-02-06T16:00:00Z",
  },
  {
    strategy: "MTUM",
    ticker: "MTUM",
    direction: "long",
    entryPrice: 238.80,
    exitPrice: 234.20,
    entryTime: "2026-02-11T16:00:00Z",
    exitTime: "2026-02-18T16:00:00Z",
  },
  {
    strategy: "MTUM",
    ticker: "MTUM",
    direction: "long",
    entryPrice: 236.50,
    exitPrice: 244.90,
    entryTime: "2026-02-20T16:00:00Z",
    exitTime: "2026-03-04T16:00:00Z",
  },
  {
    strategy: "MTUM",
    ticker: "MTUM",
    direction: "long",
    entryPrice: 245.30,
    exitPrice: 241.48,
    entryTime: "2026-03-05T16:00:00Z",
    exitTime: "2026-03-07T16:00:00Z",
  },

  // Dual Momentum Strategy trades (SPY vs EFA rotation)
  {
    strategy: "DualMomentum",
    ticker: "SPY",
    direction: "long",
    entryPrice: 590.20,
    exitPrice: 602.80,
    entryTime: "2026-01-02T16:00:00Z",
    exitTime: "2026-02-03T16:00:00Z",
  },
  {
    strategy: "DualMomentum",
    ticker: "SPY",
    direction: "long",
    entryPrice: 598.50,
    exitPrice: 610.40,
    entryTime: "2026-02-03T16:00:00Z",
    exitTime: "2026-03-03T16:00:00Z",
  },
]

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url)
  const strategy = searchParams.get("strategy")

  let trades = backtestTradesYTD.map((t) => ({
    ...t,
    pnlPercent: +((t.exitPrice - t.entryPrice) / t.entryPrice * 100).toFixed(2),
    source: "backtest" as const,
  }))

  if (strategy && strategy !== "All") {
    trades = trades.filter((t) => t.strategy === strategy)
  }

  // Sort by entryTime descending (most recent first)
  trades.sort((a, b) => new Date(b.entryTime).getTime() - new Date(a.entryTime).getTime())

  return NextResponse.json({ ok: true, trades })
}
