-- Club invite tokens: generated by org_admin/coach, shared with parents & supporters
CREATE TABLE IF NOT EXISTS club_invite_tokens (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  club_id UUID REFERENCES clubs(id) ON DELETE CASCADE,
  token TEXT UNIQUE NOT NULL,
  created_by_user_id UUID REFERENCES auth.users(id),
  expires_at TIMESTAMPTZ,
  max_uses INT,
  use_count INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Family connections: links parents/guardians to athletes within a club
CREATE TABLE IF NOT EXISTS family_connections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  parent_user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  athlete_user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  club_id UUID REFERENCES clubs(id) ON DELETE CASCADE,
  relationship TEXT, -- 'parent', 'guardian', 'friend', 'coach'
  status TEXT DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
  requested_at TIMESTAMPTZ DEFAULT NOW(),
  approved_at TIMESTAMPTZ,
  approved_by TEXT -- 'athlete' or 'admin'
);

-- Indexes for common lookups
CREATE INDEX IF NOT EXISTS idx_club_invite_tokens_token ON club_invite_tokens(token);
CREATE INDEX IF NOT EXISTS idx_club_invite_tokens_club ON club_invite_tokens(club_id);
CREATE INDEX IF NOT EXISTS idx_family_connections_parent ON family_connections(parent_user_id);
CREATE INDEX IF NOT EXISTS idx_family_connections_athlete ON family_connections(athlete_user_id);
CREATE INDEX IF NOT EXISTS idx_family_connections_status ON family_connections(status);

-- RLS for club_invite_tokens
ALTER TABLE club_invite_tokens ENABLE ROW LEVEL SECURITY;

-- Anyone can read tokens (needed for validation endpoint via service role)
CREATE POLICY "Club admins manage invite tokens" ON club_invite_tokens FOR ALL USING (
  club_id IN (SELECT id FROM clubs WHERE created_by = auth.uid())
);

-- RLS for family_connections
ALTER TABLE family_connections ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Parents see own connections" ON family_connections FOR SELECT USING (
  parent_user_id = auth.uid()
);

CREATE POLICY "Athletes see connections to them" ON family_connections FOR SELECT USING (
  athlete_user_id = auth.uid()
);

CREATE POLICY "Parents create connection requests" ON family_connections FOR INSERT WITH CHECK (
  parent_user_id = auth.uid()
);

CREATE POLICY "Athletes approve/reject connections" ON family_connections FOR UPDATE USING (
  athlete_user_id = auth.uid()
);

CREATE POLICY "Club admins manage connections" ON family_connections FOR ALL USING (
  club_id IN (SELECT id FROM clubs WHERE created_by = auth.uid())
);
